# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from qubitos.proto.quantum.pulse.v1 import grape_pb2 as quantum_dot_pulse_dot_v1_dot_grape__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in quantum/pulse/v1/grape_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class GRAPEServiceStub:
    """GRAPE service definition."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Optimize = channel.unary_unary(
            "/quantum.pulse.v1.GRAPEService/Optimize",
            request_serializer=quantum_dot_pulse_dot_v1_dot_grape__pb2.OptimizeRequest.SerializeToString,
            response_deserializer=quantum_dot_pulse_dot_v1_dot_grape__pb2.OptimizeResponse.FromString,
            _registered_method=True,
        )
        self.Cancel = channel.unary_unary(
            "/quantum.pulse.v1.GRAPEService/Cancel",
            request_serializer=quantum_dot_pulse_dot_v1_dot_grape__pb2.CancelRequest.SerializeToString,
            response_deserializer=quantum_dot_pulse_dot_v1_dot_grape__pb2.CancelResponse.FromString,
            _registered_method=True,
        )


class GRAPEServiceServicer:
    """GRAPE service definition."""

    def Optimize(self, request, context):
        """Run GRAPE optimization."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Cancel(self, request, context):
        """Cancel a running optimization."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_GRAPEServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Optimize": grpc.unary_unary_rpc_method_handler(
            servicer.Optimize,
            request_deserializer=quantum_dot_pulse_dot_v1_dot_grape__pb2.OptimizeRequest.FromString,
            response_serializer=quantum_dot_pulse_dot_v1_dot_grape__pb2.OptimizeResponse.SerializeToString,
        ),
        "Cancel": grpc.unary_unary_rpc_method_handler(
            servicer.Cancel,
            request_deserializer=quantum_dot_pulse_dot_v1_dot_grape__pb2.CancelRequest.FromString,
            response_serializer=quantum_dot_pulse_dot_v1_dot_grape__pb2.CancelResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "quantum.pulse.v1.GRAPEService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("quantum.pulse.v1.GRAPEService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class GRAPEService:
    """GRAPE service definition."""

    @staticmethod
    def Optimize(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/quantum.pulse.v1.GRAPEService/Optimize",
            quantum_dot_pulse_dot_v1_dot_grape__pb2.OptimizeRequest.SerializeToString,
            quantum_dot_pulse_dot_v1_dot_grape__pb2.OptimizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Cancel(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/quantum.pulse.v1.GRAPEService/Cancel",
            quantum_dot_pulse_dot_v1_dot_grape__pb2.CancelRequest.SerializeToString,
            quantum_dot_pulse_dot_v1_dot_grape__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
