# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: quantum/pulse/v1/hamiltonian.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'quantum/pulse/v1/hamiltonian.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"quantum/pulse/v1/hamiltonian.proto\x12\x10quantum.pulse.v1\"\xbe\x03\n\x0fHamiltonianSpec\x12\x46\n\x06\x66ormat\x18\x01 \x01(\x0e\x32\x36.quantum.pulse.v1.HamiltonianSpec.RepresentationFormat\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x19\n\x11hilbert_space_dim\x18\x03 \x01(\x05\x12\x12\n\nnum_qubits\x18\x04 \x01(\x05\x12\x1c\n\x14validation_tolerance\x18\x05 \x01(\x01\x12\x19\n\x11\x63ontrol_operators\x18\x06 \x03(\t\x12\x11\n\tvalidated\x18\x07 \x01(\x08\x12\x18\n\x10validation_error\x18\x08 \x01(\t\"\xb6\x01\n\x14RepresentationFormat\x12%\n!REPRESENTATION_FORMAT_UNSPECIFIED\x10\x00\x12&\n\"REPRESENTATION_FORMAT_PAULI_STRING\x10\x01\x12\'\n#REPRESENTATION_FORMAT_MATRIX_SPARSE\x10\x02\x12&\n\"REPRESENTATION_FORMAT_MATRIX_DENSE\x10\x03J\x04\x08\x32\x10\x65\x42\x17\n\x13io.qubitos.pulse.v1P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'quantum.pulse.v1.hamiltonian_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023io.qubitos.pulse.v1P\001'
  _globals['_HAMILTONIANSPEC']._serialized_start=57
  _globals['_HAMILTONIANSPEC']._serialized_end=503
  _globals['_HAMILTONIANSPEC_REPRESENTATIONFORMAT']._serialized_start=315
  _globals['_HAMILTONIANSPEC_REPRESENTATIONFORMAT']._serialized_end=497
# @@protoc_insertion_point(module_scope)
