# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: quantum/backend/v1/service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'quantum/backend/v1/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from qubitos.proto.quantum.backend.v1 import execution_pb2 as quantum_dot_backend_dot_v1_dot_execution__pb2
from qubitos.proto.quantum.backend.v1 import hardware_pb2 as quantum_dot_backend_dot_v1_dot_hardware__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n quantum/backend/v1/service.proto\x12\x12quantum.backend.v1\x1a\"quantum/backend/v1/execution.proto\x1a!quantum/backend/v1/hardware.proto\"4\n\x13ListBackendsRequest\x12\x17\n\x0finclude_details\x18\x01 \x01(\x08J\x04\x08\x32\x10\x65\"g\n\x14ListBackendsResponse\x12\x15\n\rbackend_names\x18\x01 \x03(\t\x12\x32\n\x08\x62\x61\x63kends\x18\x02 \x03(\x0b\x32 .quantum.backend.v1.HardwareInfoJ\x04\x08\x32\x10\x65\x32\x8c\x04\n\x15QuantumBackendService\x12\x61\n\x0c\x45xecutePulse\x12\'.quantum.backend.v1.ExecutePulseRequest\x1a(.quantum.backend.v1.ExecutePulseResponse\x12p\n\x11\x45xecutePulseBatch\x12,.quantum.backend.v1.ExecutePulseBatchRequest\x1a-.quantum.backend.v1.ExecutePulseBatchResponse\x12j\n\x0fGetHardwareInfo\x12*.quantum.backend.v1.GetHardwareInfoRequest\x1a+.quantum.backend.v1.GetHardwareInfoResponse\x12O\n\x06Health\x12!.quantum.backend.v1.HealthRequest\x1a\".quantum.backend.v1.HealthResponse\x12\x61\n\x0cListBackends\x12\'.quantum.backend.v1.ListBackendsRequest\x1a(.quantum.backend.v1.ListBackendsResponseB\x19\n\x15io.qubitos.backend.v1P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'quantum.backend.v1.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025io.qubitos.backend.v1P\001'
  _globals['_LISTBACKENDSREQUEST']._serialized_start=127
  _globals['_LISTBACKENDSREQUEST']._serialized_end=179
  _globals['_LISTBACKENDSRESPONSE']._serialized_start=181
  _globals['_LISTBACKENDSRESPONSE']._serialized_end=284
  _globals['_QUANTUMBACKENDSERVICE']._serialized_start=287
  _globals['_QUANTUMBACKENDSERVICE']._serialized_end=811
# @@protoc_insertion_point(module_scope)
