# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: quantum/common/v1/common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "quantum/common/v1/common.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1equantum/common/v1/common.proto\x12\x11quantum.common.v1"O\n\x0cTraceContext\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x0f\n\x07span_id\x18\x02 \x01(\t\x12\x16\n\x0eparent_span_id\x18\x03 \x01(\tJ\x04\x08\x32\x10\x65"1\n\tTimestamp\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x12\r\n\x05nanos\x18\x02 \x01(\x05J\x04\x08\x32\x10\x65"\xaf\x02\n\x05\x45rror\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x33\n\x08severity\x18\x02 \x01(\x0e\x32!.quantum.common.v1.Error.Severity\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x04 \x01(\t\x12\x10\n\x08trace_id\x18\x05 \x01(\t\x12/\n\ttimestamp\x18\x06 \x01(\x0b\x32\x1c.quantum.common.v1.Timestamp"x\n\x08Severity\x12\x18\n\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x11\n\rSEVERITY_INFO\x10\x01\x12\x14\n\x10SEVERITY_WARNING\x10\x02\x12\x15\n\x11SEVERITY_DEGRADED\x10\x03\x12\x12\n\x0eSEVERITY_FATAL\x10\x04J\x04\x08\x32\x10\x65"+\n\x07\x43omplex\x12\x0c\n\x04real\x18\x01 \x01(\x01\x12\x0c\n\x04imag\x18\x02 \x01(\x01J\x04\x08\x32\x10\x65\x42\x18\n\x14io.qubitos.common.v1P\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "quantum.common.v1.common_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"\n\024io.qubitos.common.v1P\001"
    _globals["_TRACECONTEXT"]._serialized_start = 53
    _globals["_TRACECONTEXT"]._serialized_end = 132
    _globals["_TIMESTAMP"]._serialized_start = 134
    _globals["_TIMESTAMP"]._serialized_end = 183
    _globals["_ERROR"]._serialized_start = 186
    _globals["_ERROR"]._serialized_end = 489
    _globals["_ERROR_SEVERITY"]._serialized_start = 363
    _globals["_ERROR_SEVERITY"]._serialized_end = 483
    _globals["_COMPLEX"]._serialized_start = 491
    _globals["_COMPLEX"]._serialized_end = 534
# @@protoc_insertion_point(module_scope)
