# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: quantum/pulse/v1/feedback.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'quantum/pulse/v1/feedback.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from qubitos.proto.quantum.pulse.v1 import sme_pb2 as quantum_dot_pulse_dot_v1_dot_sme__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fquantum/pulse/v1/feedback.proto\x12\x10quantum.pulse.v1\x1a\x1aquantum/pulse/v1/sme.proto\"\xf7\x01\n\x0e\x46\x65\x65\x64\x62\x61\x63kConfig\x12\x17\n\x0f\x63ontroller_type\x18\x01 \x01(\t\x12\x15\n\rfeedback_gain\x18\x02 \x03(\x01\x12\x19\n\x11\x66\x65\x65\x64\x62\x61\x63k_delay_ns\x18\x03 \x01(\x01\x12$\n\x1cmax_correction_amplitude_mhz\x18\x04 \x01(\x01\x12\x14\n\x0c\x63ontrol_axes\x18\x05 \x03(\t\x12>\n\x15target_density_matrix\x18\x06 \x01(\x0b\x32\x1f.quantum.pulse.v1.ComplexMatrix\x12\x18\n\x10\x66ull_gain_matrix\x18\x07 \x03(\x01J\x04\x08\x32\x10\x65\"\xf7\x01\n\x0e\x46\x65\x65\x64\x62\x61\x63kResult\x12/\n\nsme_result\x18\x01 \x01(\x0b\x32\x1b.quantum.pulse.v1.SMEResult\x12\x1a\n\x12\x63orrection_history\x18\x02 \x03(\x01\x12\x10\n\x08num_axes\x18\x03 \x01(\x05\x12\x1b\n\x13lyapunov_trajectory\x18\x04 \x03(\x01\x12\x1c\n\x14\x66\x65\x65\x64\x62\x61\x63k_energy_cost\x18\x05 \x01(\x01\x12 \n\x18\x63rossover_noise_strength\x18\x06 \x01(\x01\x12#\n\x1b\x64\x65\x63oherence_budget_consumed\x18\x07 \x03(\x01J\x04\x08\x32\x10\x65\x42\x17\n\x13io.qubitos.pulse.v1P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'quantum.pulse.v1.feedback_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023io.qubitos.pulse.v1P\001'
  _globals['_FEEDBACKCONFIG']._serialized_start=82
  _globals['_FEEDBACKCONFIG']._serialized_end=329
  _globals['_FEEDBACKRESULT']._serialized_start=332
  _globals['_FEEDBACKRESULT']._serialized_end=579
# @@protoc_insertion_point(module_scope)
